Import('RTT_ROOT')
Import('rtconfig')
from ast import Global
from building import *

cwd = GetCurrentDir()
src = []
group = []
CPPPATH = []

if rtconfig.PLATFORM in ['iccarm']:
    print("\nThe current project does not support iar build\n")
    Return('group')
elif rtconfig.PLATFORM in ['gcc']:
    src += Glob(cwd + '/fsp/src/bsp/mcu/all/*.c')
    src += [cwd + '/fsp/src/bsp/cmsis/Device/RENESAS/Source/system.c']
    src += [cwd + '/fsp/src/bsp/cmsis/Device/RENESAS/Source/startup.c']
    src += Glob(cwd + '/fsp/src/r_*/*.c')
    src += Glob(cwd + '/fsp/src/rm_*/**.c')
    src += Glob(cwd + '/intel/tinycrypt/lib/source/*.c')
    src += Glob(cwd + '/mcu-tools/MCUboot/boot/bootutil/src/*.c')
    CPPPATH = [ cwd + '/arm/CMSIS_5/CMSIS/Core/Include',
                cwd + '/fsp/inc',
                cwd + '/fsp/inc/api',
                cwd + '/fsp/inc/instances',
                cwd + '/intel/tinycrypt/lib/include',
                cwd + '/mcu-tools/MCUboot/boot/bootutil/include',
                cwd + '/fsp/src/rm_mcuboot_port/',
                cwd + '/mcu-tools/MCUboot/boot/bootutil/src',
                cwd + '/mcu-tools/MCUboot/boot/bootutil/src/rm_mcuboot_port']

elif rtconfig.PLATFORM == 'armclang':
    if GetOption('target') != 'mdk5':
        src += Glob(cwd + '/fsp/src/bsp/mcu/all/*.c')
        src += [cwd + '/fsp/src/bsp/cmsis/Device/RENESAS/Source/system.c']
        src += [cwd + '/fsp/src/bsp/cmsis/Device/RENESAS/Source/startup.c']
        src += Glob(cwd + '/fsp/src/r_*/*.c')
        src += Glob(cwd + '/intel/tinycrypt/lib/source/*.c')
        src += Glob(cwd + '/mcu-tools/MCUboot/boot/bootutil/src/*.c')
        src += Glob
        CPPPATH = [ cwd + '/arm/CMSIS_5/CMSIS/Core/Include',
                    cwd + '/fsp/inc',
                    cwd + '/fsp/inc/api',
                    cwd + '/fsp/inc/instances']

group = DefineGroup('ra', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
